function demodHCPHCPDallAgesqcgrad = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DEMODHCPHCPDALLAGESQCGRAD = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  DEMODHCPHCPDALLAGESQCGRAD = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  DEMODHCPHCPDALLAGESQCGRAD = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  demodHCPHCPDallAgesqcgrad = importfile("/local_raid2/03_user/shinwon/01_project/01_thalamusgradient/05_analysis_cmap_pmap/000_sourceData_Code/Upload_versions/demo_dHCP,HCPD_allAges_qcgrad.xlsx", "Sheet1", [2, 853]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2024-04-16 00:23:43

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 853];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":L" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["sort", "dataset", "sub_id", "ses_id_dhcp", "age_in_weeks", "age_in_years", "session", "qc_grad", "task_rest", "sex", "meanFD", "MeanFD04"];
opts.VariableTypes = ["double", "categorical", "string", "double", "double", "double", "categorical", "double", "categorical", "categorical", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "sub_id", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["dataset", "sub_id", "session", "task_rest", "sex"], "EmptyFieldRule", "auto");

% Import the data
demodHCPHCPDallAgesqcgrad = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":L" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    demodHCPHCPDallAgesqcgrad = [demodHCPHCPDallAgesqcgrad; tb]; %#ok<AGROW>
end

end