function demonkilong = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DEMONKILONG = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DEMONKILONG = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DEMONKILONG = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  demonkilong = importfile("/local_raid2/03_user/shinwon/01_project/01_thalamusgradient/05_analysis_cmap_pmap/000_sourceData_Code/Upload_versions/files/demo_nki_long.xlsx", "Sheet1", [2, 71]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2024-04-17 06:16:51

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 71];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["id", "Anonymized_ID", "age_bas1", "age_flu1", "male", "female", "sex"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["id", "Anonymized_ID"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["id", "Anonymized_ID", "sex"], "EmptyFieldRule", "auto");

% Import the data
demonkilong = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    demonkilong = [demonkilong; tb]; %#ok<AGROW>
end

end