function SleepWakedemo = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  SLEEPWAKEDEMO = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  SLEEPWAKEDEMO = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  SLEEPWAKEDEMO = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  SleepWakedemo = importfile("/local_raid2/03_user/shinwon/01_project/01_thalamusgradient/05_analysis_cmap_pmap/000_sourceData_Code/Upload_versions/files/Sleep-Wake_demo.xlsx", "Sheet2", [2, 30]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2024-04-17 10:56:02

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 30];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 72);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":BT" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["SubjectID", "ID", "Demographicsavailable1Y0N", "AgeAwake", "AgeAsleep", "Time_interval", "Sex", "FDJ_Awake", "FDJ_Sleep", "PART_GlobalID", "DEM_Sex", "DEM_Hispanic", "DEM_Race", "DEM_Income", "DEM_SES", "DX_PDD", "DX_5_ASD", "DX_5_Comorbidity", "DX_5_ASDADHD", "DX_5_GAD", "DX_5_OCD", "DX_5_Bulimia", "DX_5_ODD", "DX_5_TicDis", "SRSP_AwareT", "SRSP_CogT", "SRSP_CommT", "SRSP_MotivT", "SRSP_AutMannT", "SRSP_TotT", "VINE_CommStand", "VINE_DayStand", "VINE_SocStand", "VINE_MotStand", "VINE_DomStand", "VINE_ABCStand", "MEDS_MedNaive", "MEDS_NoMeds", "MEDS_Stimulants", "MEDS_OthADHDMed", "MEDS_Notes", "ADIRDX_Reliable", "ADIRDX_ATot", "ADIRDX_BNVTot", "ADIRDX_CTot", "ADIRDX_DTot", "CBCL_IntProbT", "CBCL_ExtProbT", "CBCL_TotProbT", "ADOS2_Version", "ADOS2_Module", "ADOS2_Reliable", "ADOS2_SocAffTotal", "ADOS2_RestRepBehTot", "ADOS2_SARRBehTot", "ADOS2_SocAffSeverity", "ADOS2_RestRepBehSeverity", "ADOS2_TotalSeverity", "ADOS2_Classification", "DAS_Battery", "DAS_VerbalStandard", "DAS_NonverbalStandard", "DAS_SpatialStandard", "DAS_GCAStandard", "RBS_Stereotypy", "RBS_SelfInjury", "RBS_Compulsive", "RBS_RitualisticSameness", "RBS_Restricted", "CSHQ_Total", "CSHQ_Classification", "RBS_Total"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["SubjectID", "MEDS_Notes", "ADIRDX_DTot"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SubjectID", "Sex", "MEDS_Notes", "ADIRDX_DTot"], "EmptyFieldRule", "auto");

% Import the data
SleepWakedemo = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":BT" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    SleepWakedemo = [SleepWakedemo; tb]; %#ok<AGROW>
end

end