function NKIsubses = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  NKISUBSES = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  NKISUBSES = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  NKISUBSES = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NKIsubses = importfile("/local_raid2/03_user/shinwon/01_project/01_thalamusgradient/05_analysis_cmap_pmap/000_sourceData_Code/Upload_versions/files/NKI_sub_ses.xlsx", "Sheet1", [2, 174]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2024-04-17 05:47:24

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 174];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":B" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["subject", "session"];
opts.VariableTypes = ["categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["subject", "session"], "EmptyFieldRule", "auto");

% Import the data
NKIsubses = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":B" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    NKIsubses = [NKIsubses; tb]; %#ok<AGROW>
end

end